language: python
python:
- '2.7'
install:
    - pip install -r requirements.txt
script: py.test tests/ -v
deploy:
  provider: pypi
  user: nuagenetworks
  password:
    secure: EnXjoD+OjwojL8Je0z3FQ2aOeR1Tqc/BO+qkXgvk0g9FfT4I+1WTwE9ZpLl5UF6c5Xvj+Pf8KnW5wui3Q+cC4ssL5qN2WSv2QqVOIHbJi67s8pQYDndCo0w2CgfcuK9vjbqpN+F1/EfEctMoFurCw979SHz+qGmxOEPzijbu0R2hmyvoJ/ES02gRPN24b+M9vdr6fE9vtiQz6ubocR7HBQ7+zvPZ8+k++89rZwB5X42kBRmHALhBYikShvbd+Ohn2EB4zGPL+/R0ah6pAbno8eGy8mqzNr7+usDow3NENIWT+8M0F3UF0/AUmkkbVyKZ00VVAayFinx7Swpj4Eb2f0X734sizLRGdAhlHs9xDsWo8SVXAYoE0JjXtzVy4rKmdniobG2vh1ENskWDoU/7AFYTrs3sy1Uz39YLMQlYlRSLumC1OeZYv4BIwPdnaiqm5NqcTI3/eJPcYTAk5blRN/onub8vdBUrPc4xD+RCs/fmzvrOVOjasVzCxPpqB0ozGVX7v7GPI/fd1ScEDS1D60V2xVCvuqoPr9C3pNbfzHeObqT57oAgmNpw/etdbvTGO/p30m1k/e0kOAZOl7+Lwe6Nl1rciasqoAKf/lS5TonwV47Qs2FQXC+JyVC7M622cV3diAyRLgGAklFtuo5pcuklv11zlZIQyIKbB40xL98=
  on:
    all_branches: true
    tags: true
    distributions: sdist bdist_wheel
    repo: nuagenetworks/monolithe
